from langgraph_temp_workflow.common.state import ProjectState
import json

def prompt_for_node_classify_pages():
    prompt = """
    Analyze this construction sheet and classify it into exactly ONE of these categories:

    - "text": If the page contains mostly Notes, Schedules, Tables, or Specifications.
    - "floor": If the page shows a Plan View, Foundation Plan, or Roof Framing Plan.
    - "section": If the page shows Detail Drawings, Wall Sections, or Connection Cuts.

    **OUTPUT FORMAT:**
    You must return a JSON object. Do not return just the word.
    Example: {"drawing_type": "floor"}
    """
    return prompt

def prompt_for_node_process_details():
    prompt = f"""
    You are a Senior Structural Detailer creating a "Standard Definition Library".
    
    ### INPUTS PROVIDED:
    1. **Layout PDF:** Shows the full page structure.
    2. **Cropped Images:** High-resolution zooms. Filenames are provided.
    3. **Text JSON:** OCR text found on the page.

    ### YOUR GOAL
    Visually group the inputs into distinct **"Detail Units"** and create a **Recipe Card** for each one.

    ---
    ### MULTIMODAL CHAIN-OF-THOUGHT PROCESS:

    **STEP 1: IDENTIFY & GROUP (The Trace)**
    - Look at the Layout PDF. Find a Title.
    - Find the Cropped Image that matches this Title.
    - *Trace:* "I matched Title 'LADDER DETAIL' to Image 'crop_005.jpg' because it is located directly above the text."

    **STEP 2: EXTRACT INGREDIENTS (Verbatim)**
    - Read the text on the leader lines.
    - **CRITICAL RULE:** Extract the material name **EXACTLY AS WRITTEN** on the drawing.
        - *Bad:* "Angle 4x4"
        - *Good:* "L4x4x1/4"
        - *Bad:* "3/4 inch Rod"
        - *Good:* "3/4\" DIA. ROD"
    - Do not expand abbreviations. Do not convert units.

    **STEP 3: DEFINE LOGIC (Fixed vs Variable)**
    - Decide if the item count is constant (Fixed) or depends on height/width (Variable).

    ---
    ### OUTPUT FORMAT (JSON List)
    [
      {{
        "detail_id": "7/S-3.2",
        "title": "LADDER DETAIL",
        "source_trace": "Matched Title at [x,y] to Image 'crop_005.jpg'",
        "visual_reasoning": "I identified this as a Ladder. It contains fixed clips and variable rails.",
        "materials": [
          {{
            "item_name": "L4x4x1/4x0'-3\"",  <-- EXACT TEXT FROM PDF
            "material_type": "L",
            "qty_rule": "FIXED: 2",
            "notes": "Base connection clips"
          }}
        ],
        "fabrication": {{ ... }}
      }}
    ]
    """
    return prompt

# def prompt_for_node_process_plans():
#     prompt = """
#     You are a Forensic Structural Surveyor. You are analyzing a high-resolution image crop from a construction plan.

#     ### YOUR MISSION
#     1. **CLASSIFY** the image crop as either a **Plan View** (Drawing) or a **Definition Schedule** (Table/Legend).
#     2. **EXTRACT** the relevant data based on that classification.

#     ### MULTIMODAL CHAIN-OF-THOUGHT PROCESS (Think Step-by-Step):

#     **STEP 1: CLASSIFY THE CROP (Set 'content_type')**
#     - Look at the image.
#     - If it shows lines, walls, grids, and symbols -> It is **"Plan_View"**.
#     - If it shows rows, columns, text definitions, or a legend -> It is **"Definition_Schedule"**.
#     - If it shows paragraphs of text -> It is **"Notes"**.

#     **STEP 2: EXTRACT DATA (Based on Type)**

#     **IF "Plan_View": (Extract Instances)**
#     - **HSS Columns:** Find black squares. Read label (e.g., "HSS5x5"). Record Grid Intersection (e.g., "B-2").
#     - **WF Beams:** Find beam lines. Read label (e.g., "W24x62"). Trace line to Start/End Grids.
#     - **Symbols:** Find Hexagons (<1>), Circles (7/S-3.2).
#         - *CRITICAL:* Find the **Dimension Text** written next to the symbol (e.g., "13'-10\""). This is the Wall Length.
#         - *CRITICAL:* Find the **"R.O." Dimension** for windows.

#     **IF "Definition_Schedule": (Extract Rules)**
#     - **Transcribe the Data:** Read the rows and columns.
#     - *Example:* "Shear Wall Schedule -> Symbol <1> = 5/8 inch bolt @ 16 oc".
#     - *Example:* "Lintel Schedule -> 4ft opening = L4x4x3/8".
#     - Store this in the `schedules` list.

#     **IF "Notes": (Extract Globals)**
#     - Extract key rules (e.g., "T/BEAM = 18'-3 1/2\"").

#     **STEP 3: FINAL OUTPUT**
#     - Map your findings to the strict JSON schema below.
#     """
#     return prompt

def prompt_for_node_process_plans():
    prompt = """
    You are a Forensic Structural Surveyor. You are analyzing a construction plan using a **Global View** (Full Sheet) and a series of **High-Resolution YOLO Crops**.

    ### THE SITUATION
    - The crops were generated by an object detection model (YOLO).
    - **WARNING:** Crops may be overlapping, redundant, or cut off (e.g., a title might be in one crop and the table body in another).
    - **YOUR JOB:** Synthesize this information. Use the Global View for context/location and the Crops for reading specific text/dimensions.

    ### MULTIMODAL CHAIN-OF-THOUGHT PROCESS (Think Step-by-Step):

    **STEP 1: CLASSIFY & CONTEXTUALIZE**
    - Look at the specific Crop. Compare it to the Global View.
    - **Is it a Plan View?** (Drawing of the building).
    - **Is it a Definition Schedule?** (Table defining symbols/materials).
    - **Is it Notes?** (Text blocks).
    - *Reasoning:* "This crop shows a grid of text. Looking at the Global View, this is the bottom-left corner, which corresponds to the Shear Wall Schedule."

    **STEP 2: EXTRACT DATA (Handle Fragmentation)**

    **IF "Plan_View" (The Map):**
    - **HSS Columns:** Find black squares. Read the label (e.g., "HSS5x5"). 
        - *Context Check:* If the Grid Bubble is cut off in the crop, look at the Global View to confirm the Grid Intersection (e.g., "B-2").
    - **WF Beams:** Find beam lines and labels (e.g., "W24x62").
    - **Symbols:** Find Hexagons (<1>), Circles (7/S-3.2).
        - *CRITICAL:* Find the **Dimension Text** written next to the symbol (e.g., "13'-10\""). This is the Wall Length.
        - *CRITICAL:* Find the **"R.O." Dimension** for windows.

    **IF "Definition_Schedule" (The Legend):**
    - **Reconstruct the Table:** If the crop only shows rows (no header), look at the Global View to identify which schedule this is (e.g., "Shear Wall Schedule").
    - **Transcribe Data:** Read the rows.
        - *Example:* "Symbol <1> = 5/8 inch bolt @ 16 oc".
        - *Example:* "Lintel Schedule -> 4ft opening = L4x4x3/8".
    - **Deduplication:** If you see the same row in multiple overlapping crops, only record it once.

    **IF "Notes":**
    - Extract global rules (e.g., "T/BEAM = 18'-3 1/2\"").

    **STEP 3: FINAL OUTPUT**
    - Map your findings to the strict JSON schema below.
    - Ensure `content_type` is correctly set so the system knows where to store the data.
    """
    return prompt

# def node_agent_4_merger(state: ProjectState):

#     prompt = f"""
#     You are the Senior Structural Estimator. You have received raw data from your field surveyors (Agent 1, 2, and 3).
#     Your job is to **INTERLACE** this information to produce the Final Material Takeoff.

#     ### INPUT DATA
#     1. **RAW PLAN DATA (From Agent 2):** 
#     {json.dumps(state['raw_plan_data'], indent=2)}
    
#     2. **DETAIL LIBRARY (BOMs from Agent 3):** 
#     {json.dumps(state['detail_library'], indent=2)}
    
#     3. **TEXT RULES (From Agent 1):** 
#     {state['general_rules']}

#     ### YOUR EXECUTION PLAN (Step-by-Step Logic)

#     **STEP 1: RESOLVE HSS COLUMNS (Cross-Reference Floor & Roof)**
#     *   Take HSS counts from Floor Plan Data.
#     *   Find the "Top of Steel" elevation note in Roof Plan Data (e.g., "T/BEAM = 18'-3 1/2\"").
#     *   *Calculation:* Count * (Roof Elevation - 0).
#     *   *Goal:* Total Linear Feet of HSS.

#     **STEP 2: RESOLVE WF BEAMS (Trace Grids)**
#     *   Take WF labels from Roof Plan Data.
#     *   Use the "length_text" found by Agent 2 (e.g., "27'-0\"").
#     *   *Goal:* Total Linear Feet of WF.

#     **STEP 3: RESOLVE SYMBOLS (The "Lookup" Logic)**
#     *   **Detail Callouts:** Look at symbols like "7/S-3.2" found on the Floor Plan.
#         *   *Action:* Look up "7/S-3.2" in the **DETAIL LIBRARY**.
#         *   *Action:* If Library says "Ladder", and Floor Plan says "Qty: 1", add 1 Ladder to the list.
#         *   *Action:* If Library says "MC6x15.1 Rails", add those channels to the C-Channel list.
#     *   **Shear Walls:** Look at "Hexagon 1" found on Floor Plan.
#         *   *Action:* Look up "Hexagon 1" in the **TEXT RULES** (Shear Wall Schedule).
#         *   *Rule Found:* "5/8 inch Bolt @ 16 inch spacing".
#         *   *Dimension Found:* Agent 2 saw "13'-10\"" next to the hexagon.
#         *   *Math:* (13.83 ft * 12) / 16 inches = 10.3 -> Round up -> 11 Bolts.
#         *   *Goal:* Add 11 Bolts to the ROD list.

#     **STEP 4: RESOLVE LINTELS (The "R.O." Logic)**
#     *   Look at "Window Tag <6>" found on Floor Plan.
#     *   *Dimension Found:* Agent 2 saw "4'-0\" R.O.".
#     *   *Rule Lookup:* Check Lintel Schedule in **TEXT RULES**. "If width < 5ft, use L4x4x3/8".
#     *   *Math:* 4.0 ft + 1.33 ft (bearing) = 5.33 ft.
#     *   *Goal:* Add 5.33 ft of L4x4x3/8 to the L-Angle list.

#     ### FINAL OUTPUT GOALS
#     Produce a JSON summary satisfying these 6 aims:
#     1. **Material Takeoff:** List every HSS, WF, C, L, FB, ROD found.
#     2. **Total Weight:** Sum of (Length * Lbs/ft).
#     3. **Member Count:** Total count of beams, columns, and assemblies.
#     4. **Weld Inches:** Sum of welds defined in the Detail Library.
#     5. **Hole Count:** Sum of holes defined in connections and base plates.
#     6. **Bolt Count:** Sum of Anchor Bolts (from Shear Walls/Columns) + Structural Bolts.

#     ### OUTPUT JSON STRUCTURE
#     {{
#       "final_bill_of_materials": [
#         {{
#           "description": "HSS 5x5x5/16",
#           "total_qty": 5,
#           "total_linear_feet": 91.45,
#           "logic_trace": "Found 5 on Floor Plan. Applied 18.29' height from Roof Plan."
#         }},
#         {{
#           "description": "Simpson Titen HD 5/8",
#           "total_qty": 45,
#           "logic_trace": "Calculated from 4 Shear Walls (Hexagon 1) using lengths 13'-10\", 10'-4\", etc."
#         }}
#       ]
#     }}
#     """
#     return prompt

# def prompt_for_agent_4_merger(state):
#     return f"""
#     You are the Senior Structural Estimator. You are performing a **Multimodal Chain-of-Thought (CoT)** analysis to generate a precise Steel Takeoff.

#     ### INPUT DATA (The "Multimodal" Context):
#     1. **VISUAL OBSERVATIONS (Plan Data):** {json.dumps(state['raw_plan_data'], indent=2)}
#     2. **VISUAL DETAILS (BOM Library):** {json.dumps(state['detail_library'], indent=2)}
#     3. **TEXTUAL RULES (Schedules):** {state['general_rules']}

#     ---
#     ### CHAIN-OF-THOUGHT PROCESS (Follow these 5 Steps):

#     **STEP 1: GATHER & CLASSIFY**
#     - List all unique material types found in the Plan Data (e.g., "I see HSS5x5, W24x62, Hexagon 1").
#     - List all definitions found in the Library/Rules (e.g., "Hexagon 1 = 5/8 bolt", "Detail 7 = Ladder").

#     **STEP 2: ANALYZE SYSTEMATICALLY (The "Look Up")**
#     - For every item in Step 1, find its matching rule.
#     - *Thought:* "I see Hexagon <1> on the plan. I check the Text Rules. It says <1> is a Shear Wall with 5/8 bolts at 16oc."
#     - *Thought:* "I see Symbol 7/S-3.2. I check the Detail Library. It contains MC6x15.1 rails."

#     **STEP 3: CONNECT INSIGHTS (The "Geometry Link")**
#     - Connect the **Object** to its **Dimension**.
#     - *Thought:* "The Hexagon <1> is next to a wall labeled 13'-10\". Therefore, the Wall Length is 13.83 ft."
#     - *Thought:* "The HSS Column is a vertical member. The Roof Note says Top of Steel is 18.29'. Therefore, Column Height is 18.29 ft."

#     **STEP 4: EXECUTE LOGIC (The Math)**
#     - Apply the specific Linear Feet formulas:
#         - **W/HSS Beam:** Sum of lengths found on plan.
#         - **W/HSS Column:** Count * 18.29.
#         - **Channel (Stair/Ladder):** Count * 18.29.
#         - **Angle (Lintel):** Window Width + 1.33 ft.
#         - **Rod (Anchor):** (Wall Length / Spacing) * 1.5 ft.

#     **STEP 5: VALIDATE & FORMAT**
#     - Check: Did I calculate Linear Feet for every item?
#     - Check: Did I separate Bolts/Holes/Welds?
#     - Output the final JSON.

#     ---
#     ### OUTPUT FORMAT
#     Return the `FinalEstimation` JSON object. 
#     In the `logic_trace` field, write a summary of your Step 3 & 4 reasoning (e.g., "Found 3 walls. Lengths: 10, 12, 14. Applied 16oc spacing rule.").
#     """

def prompt_for_agent_4_merger(graph_data):
    """
    Accepts the list of dictionaries returned by Neo4j (graph_data).
    """
    return f"""
    You are the Senior Structural Estimator. You are performing a **Multimodal Chain-of-Thought (CoT)** analysis to generate a precise Steel Takeoff.

    ### INPUT DATA (From Knowledge Graph):
    Here is the list of every item found on the plans, automatically linked to its definition:
    {json.dumps(graph_data, indent=2)}

    ---
    ### CHAIN-OF-THOUGHT PROCESS (Follow these 5 Steps):

    **STEP 1: GATHER & CLASSIFY**
    - Scan the input list. Identify items by 'Type' (Member vs Symbol).
    - Note which items have 'Detail_BOM' (Recipes) or 'Rule_Specs' (Schedules) attached.

    **STEP 2: ANALYZE SYSTEMATICALLY (The "Look Up")**
    - The Graph has already done the lookup for you!
    - *Thought:* "Item 'Hexagon 1' has Rule_Specs: '5/8 bolt @ 16oc'. I don't need to search for it."
    - *Thought:* "Item '7/S-3.2' has Detail_BOM: [{{'mat': 'MC6x15.1', 'rule': 'Variable'}}]. I use this recipe."

    **STEP 3: CONNECT INSIGHTS (The "Geometry Link")**
    - Look at the 'Dimension' field for each item.
    - *Thought:* "The Hexagon 1 has Dimension: '13'-10\"'. This is the Wall Length."
    - *Thought:* "The HSS Column has no dimension. I will use the Global Height (18.29')."

    **STEP 4: EXECUTE LOGIC (The Math)**
    - Apply the specific Linear Feet formulas:
        - **W/HSS Beam:** Sum of lengths found in 'Dimension' or estimated from Grid Location.
        - **W/HSS Column:** Count * 18.29.
        - **Channel (Stair/Ladder):** Count * 18.29.
        - **Angle (Lintel):** Window Width (from Dimension) + 1.33 ft.
        - **Rod (Anchor):** 
            1. Parse 'Rule_Specs' to find spacing (e.g. "16oc" -> 16 inches).
            2. Formula: `((Wall Length / Spacing) + 1) * 1.5 ft`.

    **STEP 5: VALIDATE & FORMAT**
    - Check: Did I calculate Linear Feet for every item?
    - Check: Did I separate Bolts/Holes/Welds?
    - Output the final JSON.

    ---
    ### OUTPUT FORMAT
    Return the `FinalEstimation` JSON object. 
    In the `logic_trace` field, write a summary of your Step 3 & 4 reasoning.
    """
    

